### ISSUE TITLE
Make it restartless.

### ISSUE THREAD

**Issue by Chris2011** [swdotcom/swdc-netbeans#1]
After installation, I need to restart my IDE, please make the plugin restartless. Thx.

**Comment by andrewhli** [comment]
Hi there, are restartless plugins common/normal for Netbeans? Let us know a good example of a restartless plugin, and we'll get the feature in. Thanks!

**Comment by Chris2011** [comment]
Yes it is, if you don't really need to have a special logic for that stuff, you don't need to restart the whole IDE. If you have a lot of plugins, a lot of open projects and a running virus scanner under Windows and and and, it can take several seconds/minutes that NetBeans is ready to use again after a restart. Plugins nowadays are often restartless.

Here is a list:
http://plugins.netbeans.org/plugin/50171/display-readme-files-in-project-view (https://github.com/Chris2011/readmeinprojectview)
http://plugins.netbeans.org/plugin/68372/atmel-plugin (https://github.com/ericsonj/atmel-plugin)

In general, it is only a flag. If you use maven, You can find it here: https://github.com/raydac/netbeans-mmd-plugin/blob/a9b408fcf44b96f5123d54597d2fff42c93f4e37/mind-map/nb-mind-map/pom.xml#L99

If u use ant, you can do it via the project properties: 
![image](https://user-images.githubusercontent.com/795658/53821047-4e59bd80-3f6d-11e9-86a9-aed6d10a3f4b.png)

**Comment by brettmstevens7** [comment]
Cool, thanks for the suggestion and helpful links. We'll add this soon.

**Comment by brettmstevens7** [comment]
Hi @Chris2011, we made our plugin restartless in the last version. Thanks again!

**Comment by Chris2011** [comment]
Great, thx :)
