### ISSUE TITLE
Move "Code Time" menu entry into Tools menu

### ISSUE THREAD

**Issue by Chris2011** [swdotcom/swdc-netbeans#2]
Unfortunately, there is no documentation where I can find how to use it, so I looked into the code to find whether there is an action or not. I didn't expect it inside of the main menu but yes it is there and in front of files. This shouldn't happen at all. I would prefer to add the whole Code Time menu as a submenu entry into the Tools section.

**Comment by andrewhli** [comment]
Yeah - we've been trying to solve this since yesterday and haven't been able to figure it out yet from the docs. Going to try fixing it today. Let me know if there are any helpful resources.

**Comment by Chris2011** [comment]
You can have a look here: https://github.com/junichi11/netbeans-vagrant-plugin/blob/aba6b1d057ccf2e86a0503a0b0e1596ce75cb6a9/vagrant/src/org/netbeans/modules/vagrant/ui/actions/VagrantActionMenu.java#L67 or here: https://github.com/jeddict/jeddict/blob/29822e80bbb7f8387997bb137b9e8c95ec1ee37a/jpa-modeler/src/main/java/io/github/jeddict/jpa/modeler/navigator/overrideview/OverrideViewNavigatorComponent.java#L49 or here: https://github.com/fungl164/JConsole/blob/master/src/org/stagezero/jconsole/JConsoleTopComponent.java#L22

**Comment by andrewhli** [comment]
Hi Chris, we fixed the menu bar today to show Code Time in the tools menu. Could you download the latest version (1.4) in the Netbeans marketplace and let me know if you see anything else?

**Comment by Chris2011** [comment]
Thx, will test it.

**Comment by Chris2011** [comment]
It is working. Thx.
